# Generated by Django 4.0.1 on 2022-03-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message_updated_at_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
